### ISSUE TITLE
Syntax error on line 7

### ISSUE THREAD

**Issue by alielbashir** [nyahmet/impytool#2]
The library version currently on the repo won't run and returns the following error:
```py
  File "/home/ali/PycharmProjects/impylib/impytool/impytool/main.py", line 7
    img = cv2.imread(image:str,0)
                          ^
SyntaxError: invalid syntax
```
This is due to a change introduced in pr #1  , where a [Type Hint](https://www.python.org/dev/peps/pep-0484/#type-definition-syntax) was written inside a function call, whereas they can only be used in function definitions.
https://github.com/nyahmet/impytool/blob/0c798a253b6d956a8fbcd8db933f3fa317dbf657/impytool/main.py#L5-L9

**Comment by nyahmet** [comment]
Thank you. I edited the wrong line.
